# Generated by Django 4.0.6 on 2022-08-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_principal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
