# Generated by Django 4.1 on 2022-08-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_alter_principal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lunch/'),
        ),
    ]
