# Generated by Django 4.1 on 2022-08-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_alter_principal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lunch/'),
        ),
    ]
