# Generated by Django 4.1 on 2022-08-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_drink_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lunch/'),
        ),
    ]
